//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WildLifeTracker
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class game_reserve_dbEntities : DbContext
    {
        public game_reserve_dbEntities()
            : base("name=game_reserve_dbEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblanimal> tblanimals { get; set; }
        public virtual DbSet<tblcategory> tblcategories { get; set; }
        public virtual DbSet<tblgpstracking> tblgpstrackings { get; set; }
    }
}
