//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WildLifeTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblanimal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblanimal()
        {
            this.tblgpstrackings = new HashSet<tblgpstracking>();
        }
    
        public int animalId { get; set; }
        public string animalName { get; set; }
        public System.DateTime createdAt { get; set; }
        public string gpsDeviceId { get; set; }
        public int categoryId { get; set; }
    
        public virtual tblcategory tblcategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblgpstracking> tblgpstrackings { get; set; }
    }
}
