//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WildLifeTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblgpstracking
    {
        public int trackingId { get; set; }
        public int animalId { get; set; }
        public double latitude { get; set; }
        public double longitude { get; set; }
        public System.DateTime createdAt { get; set; }
    
        public virtual tblanimal tblanimal { get; set; }
    }
}
